import {
  MoonStar,
  Sun,
  House,
  Send,
  Settings,
  Search,
  LibraryBig,
  ShoppingBasket,
  CircleUserRound,
  CirclePlus,
  SearchIcon,
  LogOut,
  UserPen,
  ChevronRight,
  BotMessageSquare,
  Heart,
  Share2,
  Clipboard,
  CookingPot,
  Crown,
  Star,
  Zap,
  Shield,
  Sparkles,
  ChefHat,
  BookOpen,
  Users,
  Download,
  Check,
  X,
  Info,
  ChevronLeft,
  Croissant,
  PlusIcon,
  Palette,
  HelpCircle,
  Settings2,
} from 'lucide-react-native';
import GoogleIcon from './google';
import AppleIcon from './apple';
import { iconWithClassName } from '~/lib/iconWithClassName';

iconWithClassName(MoonStar);
iconWithClassName(Sun);
iconWithClassName(House);
iconWithClassName(Send);
iconWithClassName(Settings);
iconWithClassName(Search);
iconWithClassName(LibraryBig);
iconWithClassName(ShoppingBasket);
iconWithClassName(CircleUserRound);
iconWithClassName(CirclePlus);
iconWithClassName(SearchIcon);
iconWithClassName(LogOut);
iconWithClassName(UserPen);
iconWithClassName(ChevronRight);
iconWithClassName(BotMessageSquare);
iconWithClassName(Heart);
iconWithClassName(Share2);
iconWithClassName(Clipboard);
iconWithClassName(CookingPot);
iconWithClassName(Crown);
iconWithClassName(Star);
iconWithClassName(Zap);
iconWithClassName(Shield);
iconWithClassName(Sparkles);
iconWithClassName(ChefHat);
iconWithClassName(BookOpen);
iconWithClassName(Users);
iconWithClassName(Download);
iconWithClassName(Check);
iconWithClassName(X);
iconWithClassName(Info);
iconWithClassName(ChevronLeft);
iconWithClassName(Croissant);
iconWithClassName(PlusIcon);
iconWithClassName(Palette);
iconWithClassName(HelpCircle);
iconWithClassName(Settings2);

export {
  MoonStar,
  Sun,
  House,
  Send,
  Settings,
  Search,
  LibraryBig,
  ShoppingBasket,
  CircleUserRound,
  CirclePlus,
  GoogleIcon,
  AppleIcon,
  SearchIcon,
  LogOut,
  UserPen,
  ChevronRight,
  BotMessageSquare,
  Heart,
  Share2,
  Clipboard,
  CookingPot,
  Crown,
  Star,
  Zap,
  Shield,
  Sparkles,
  ChefHat,
  BookOpen,
  Users,
  Download,
  Check,
  X,
  Info,
  ChevronLeft,
  Croissant,
  PlusIcon,
  Palette,
  HelpCircle,
  Settings2,
};
